-- Plain SQL queries
SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'COURSE_INFO';

SELECT ZIP_CODE, CITY, STATE AS State_Name FROM ZIPCODE_INFO;

SELECT DISTINCT STATE FROM ZIPCODE_INFO;

SELECT STUDENT_ID, CONCAT(STUDENT_FIRST_NAME, ' ', STUDENT_LAST_NAME) AS Student_Name FROM STUDENT_INFO;

SELECT CONCAT(ZIP_CODE, ', ', CITY, ', ', STATE) AS Address FROM ZIPCODE_INFO;

SELECT COURSE_NAME FROM COURSE_INFO;

SELECT COURSE_NAME, COST FROM COURSE_INFO;

SELECT * FROM COURSE_INFO;

SELECT INSTRUCTOR_LAST_NAME, ZIP_CODE FROM INSTRUCTOR_INFO;

SELECT DISTINCT ZIP_CODE FROM STUDENT_INFO;

SELECT STUDENT_FIRST_NAME, STUDENT_LAST_NAME FROM STUDENT_INFO;

SELECT CITY, STATE, ZIP_CODE FROM ZIPCODE_INFO;

-- SELECT using WHERE
SELECT STUDENT_ID, SECTION_ID, NUMERIC_GRADE FROM GRADE_INFO WHERE GRADE_TYPE_CODE = 'FI';

SELECT ZIP_CODE, CITY FROM ZIPCODE_INFO WHERE STATE = 'MI';

SELECT CONCAT(S.STUDENT_FIRST_NAME, ' ', S.STUDENT_LAST_NAME) AS Student_Name 
FROM STUDENT_INFO S 
JOIN ENROLLMENT_INFO E ON S.STUDENT_ID = E.STUDENT_ID 
WHERE E.ENROLLMENT_DATE >= '1999-01-01' AND E.ENROLLMENT_DATE <= '1999-01-31' 
ORDER BY Student_Name ASC;

SELECT SECTION_ID, INSTRUCTOR_ID FROM SECTION_INFO WHERE COURSE_NO IN (10, 20) ORDER BY INSTRUCTOR_ID ASC;

SELECT STUDENT_ID, SECTION_ID, NUMERIC_GRADE FROM GRADE_INFO ORDER BY SECTION_ID ASC, NUMERIC_GRADE DESC;

SELECT COURSE_NO, COURSE_NAME, COST FROM COURSE_INFO WHERE COURSE_NAME LIKE '%Intro%';

SELECT * FROM COURSE_INFO WHERE COURSE_NAME LIKE '%a__';

SELECT CONCAT(STUDENT_FIRST_NAME, ' ', STUDENT_LAST_NAME) AS Student_Name FROM STUDENT_INFO WHERE STUDENT_ID BETWEEN 300 AND 350;

SELECT * FROM COURSE_INFO WHERE COST BETWEEN 4000 AND 7000;

SELECT INSTRUCTOR_FIRST_NAME FROM INSTRUCTOR_INFO WHERE INSTRUCTOR_LAST_NAME = 'Schumer';

SELECT INSTRUCTOR_FIRST_NAME FROM INSTRUCTOR_INFO WHERE INSTRUCTOR_LAST_NAME <> 'Schumer';

SELECT COURSE_NAME, COST FROM COURSE_INFO WHERE COST > 4000;

SELECT COURSE_NAME, COST FROM COURSE_INFO WHERE COST BETWEEN 3000 AND 7000;

SELECT COURSE_NAME, COST FROM COURSE_INFO WHERE COST IN (4000, 4500);

SELECT STUDENT_FIRST_NAME, STREET_ADDRESS FROM STUDENT_INFO WHERE STUDENT_LAST_NAME LIKE 'S%';

SELECT STUDENT_FIRST_NAME, STREET_ADDRESS FROM STUDENT_INFO WHERE STUDENT_LAST_NAME LIKE '_o%';

SELECT INSTRUCTOR_FIRST_NAME FROM INSTRUCTOR_INFO WHERE INSTRUCTOR_LAST_NAME NOT LIKE 'S%';

SELECT COURSE_NAME, COST FROM COURSE_INFO WHERE COST BETWEEN 4000 AND 4500 AND COURSE_NAME LIKE 'I%';

SELECT COURSE_NAME, COST, COURSE_PREREQUISITE FROM COURSE_INFO WHERE (COST = 2000 AND COURSE_PREREQUISITE = 20) OR COURSE_PREREQUISITE = 25;

SELECT COURSE_NAME, COST, COURSE_PREREQUISITE FROM COURSE_INFO WHERE COST = 2000 OR COURSE_PREREQUISITE IN (20, 25);

SELECT * FROM COURSE_INFO WHERE COURSE_PREREQUISITE IS NULL;

SELECT STUDENT_LAST_NAME FROM STUDENT_INFO WHERE ZIP_CODE IN ('10048', '11102', '11209');

SELECT INSTRUCTOR_FIRST_NAME, INSTRUCTOR_LAST_NAME FROM INSTRUCTOR_INFO WHERE LOWER(INSTRUCTOR_LAST_NAME) LIKE '%i%' AND ZIP_CODE = '10025';

SELECT COURSE_NAME FROM COURSE_INFO WHERE COURSE_PREREQUISITE IS NOT NULL AND COST < 1100;

SELECT DISTINCT COST FROM COURSE_INFO WHERE COURSE_PREREQUISITE IS NULL;

SELECT COURSE_NO, COURSE_NAME FROM COURSE_INFO WHERE COURSE_PREREQUISITE IS NULL ORDER BY COURSE_NAME ASC;

SELECT COURSE_NO, COURSE_NAME FROM COURSE_INFO WHERE COURSE_PREREQUISITE IS NULL ORDER BY COURSE_NAME DESC;

SELECT CITY FROM ZIPCODE_INFO WHERE STATE IN ('NY', 'CT', 'New York', 'Connecticut') ORDER BY ZIP_CODE ASC;

SELECT ZIP_CODE, STUDENT_FIRST_NAME, STUDENT_LAST_NAME FROM STUDENT_INFO WHERE STUDENT_LAST_NAME = 'Graham' ORDER BY ZIP_CODE DESC, STUDENT_FIRST_NAME ASC;

SELECT CONCAT(CITY, ', ', STATE) AS City_State FROM ZIPCODE_INFO;

SELECT CONCAT(UPPER(LEFT(STUDENT_FIRST_NAME, 1)), LOWER(SUBSTRING(STUDENT_FIRST_NAME, 2, LEN(STUDENT_FIRST_NAME)))) AS Formatted_First_Name FROM STUDENT_INFO;

SELECT CONCAT(INSTRUCTOR_FIRST_NAME, ', ', INSTRUCTOR_LAST_NAME) AS Instructor_Name FROM INSTRUCTOR_INFO;

SELECT COST, COST + 10 AS Cost_Plus_10, COST - 20 AS Cost_Minus_20, COST * 30 AS Cost_Mul_30, COST / 5 AS Cost_Div_5 FROM COURSE_INFO;

SELECT DISTINCT NUMERIC_GRADE, CAST(NUMERIC_GRADE / 2.0 AS INT) AS Half_Grade FROM GRADE_INFO;

-- SELECT with TO_CHAR/DECODE/IS NULL
SELECT FORMAT(COST, '#,##0') AS Formatted_Cost FROM COURSE_INFO WHERE COURSE_NO < 25;

SELECT FORMAT(COST, '$#,##0.00') AS Formatted_Cost FROM COURSE_INFO;

SELECT COURSE_NO, COURSE_NAME, ISNULL(CAST(COURSE_PREREQUISITE AS VARCHAR), 'Not Applicable') AS Prerequisite FROM COURSE_INFO;

SELECT CITY, STATE, CASE WHEN STATE = 'NY' THEN 'New York' WHEN STATE = 'NJ' THEN 'New Jersey' ELSE 'Others' END AS State_Name FROM ZIPCODE_INFO;
