-- 1) Table Name: ZIPCODE_INFO
ALTER TABLE ZIPCODE_INFO
ALTER COLUMN CITY VARCHAR(25);

ALTER TABLE ZIPCODE_INFO
ADD STATE VARCHAR(2);

-- 2) Table Name: INSTRUCTOR_INFO
ALTER TABLE INSTRUCTOR_INFO
ALTER COLUMN INSTRUCTOR_FIRST_NAME VARCHAR(25);

ALTER TABLE INSTRUCTOR_INFO
ALTER COLUMN INSTRUCTOR_LAST_NAME VARCHAR(25);

ALTER TABLE INSTRUCTOR_INFO
ADD STREET_ADDRESS VARCHAR(50);

ALTER TABLE INSTRUCTOR_INFO
ADD ZIP_CODE VARCHAR(5);

-- 3) Table Name: COURSE_INFO
ALTER TABLE COURSE_INFO
ADD COURSE_NAME VARCHAR(50);

ALTER TABLE COURSE_INFO
ADD COURSE_PREREQUISITE NUMERIC(8,0);

ALTER TABLE COURSE_INFO
ALTER COLUMN COST NUMERIC(9,2);

-- 4) Table Name: STUDENT_INFO
ALTER TABLE STUDENT_INFO
ALTER COLUMN STUDENT_FIRST_NAME VARCHAR(25);

ALTER TABLE STUDENT_INFO
ALTER COLUMN STUDENT_LAST_NAME VARCHAR(25);

ALTER TABLE STUDENT_INFO
ADD STREET_ADDRESS VARCHAR(50);

ALTER TABLE STUDENT_INFO
ADD ZIP_CODE VARCHAR(5);

-- 5) Table Name: SECTION_INFO
ALTER TABLE SECTION_INFO
ALTER COLUMN SECTION_NO NUMERIC(3,0);

ALTER TABLE SECTION_INFO
ADD LOCATION VARCHAR(50);

ALTER TABLE SECTION_INFO
ADD CAPACITY NUMERIC(3,0);

-- 6) Table Name: ENROLLMENT_INFO
ALTER TABLE ENROLLMENT_INFO
ADD ENROLLMENT_DATE DATE;

-- 7) Table Name: GRADE_INFO
ALTER TABLE GRADE_INFO
ALTER COLUMN GRADE_CODE_OCCURANCE NUMERIC(38,0);

ALTER TABLE GRADE_INFO
ADD NUMERIC_GRADE NUMERIC(3,0);
